### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by maxmeyer** [net1957/ProxyCheck#1]
@net1957 Thanks a lot for making this application available to the public! Sorry for the long time till I gave you feedback.

1. Easy to use UI
    * I like your lean UI
    * What would help, would be some kind of authentication - at best with support for LDAP

2. Compressing the Proxy.pac 
    * Unfortunately does not work in my setup
    * Does it work both with files and pasted proxy.pac?
    * Disable the button for compression via ENV? (This might irritate supporters)

3. Proxy.pac URLs
    * I've got a limited set of Proxy.pac-URLs
    * Would it be possible to have a dropdown list I can configure via ENV?

4. Provide Docker Image
    
    Would you mind to provide a docker image?

**Comment by net1957** [comment]
Thanks for your feedback.

1. UI
   - Authentication seems a bit overkill. No sensitive information are show. Do you have a specific use case ?
2.  Compressing
  - Will look at it
  - The entry is directly passed to ProxyPacRb::Parser#parse, so url or script content should work.
  - Disable button: Should not be too difficult
3. URLS
  - Will look at it
4. Docker
  - I'm a little new at it but should be possible. Similar to Vagrant in this case

Cheers

**Comment by maxmeyer** [comment]
> 1. Authentication

You're right. But if you start adding some kind of settings (urls for proxy.pacs) via UI this might be interesting.

> 3. URLS

I created #4 for this.

**Comment by net1957** [comment]
Compression use the default of ProxyPacRb::ProxyPacCompressor.new.compress

Any idea?

**Comment by net1957** [comment]
See compress branch. I changed some value for compression
