### ISSUE TITLE
Split up forms: Compress vs. Validate Proxy.pac

### ISSUE THREAD

**Issue by maxmeyer** [net1957/ProxyCheck#5]
I would suggest to split up the two use cases:

* Compress Proxy.pac
* Validate Proxy.pac

and use different forms for this.

**Comment by net1957** [comment]
can you try with the compress branch and give me some feedback?

**Comment by maxmeyer** [comment]
Yes, sure.

**Comment by net1957** [comment]
merged in 57d5ea5 the #6

**Comment by maxmeyer** [comment]
Thanks for working on this again. :-D
